### ISSUE TITLE
Linking to event page 

### ISSUE THREAD

**Issue by rburch** [BugBuster1701/contao-banner-bundle#19]
When trying to link to an event page within the site as an external link you get a 404 error.

**Comment by BugBuster1701** [comment]
Which Version do you use for Contao and for Banner Bundle? 
What does such a link look like?
Can it be opened in the browser?

**Comment by rburch** [comment]
Thanks for responding. It's Contao 4.4.18.  The banner Module I think is 1.0. It works fine if the link an outside site, but my client often like to make banners for events they have in Contao.
I did a work around by making a hidden redirect page in Contao and linking the banner to that.

**Comment by BugBuster1701** [comment]
Okay, I'll try to reconstruct that.
But not until next week, after the Contao conference.

**Comment by BugBuster1701** [comment]
I tried to recreate the problem.
For this I took the Contao demo.
But I can't see any problems.

Is the link in the browser, which is taken as source, identical to the link which calls the banner module and generates a 404 error? 

Are there any special characters in the URL?

**Comment by rburch** [comment]
Sorry it took me so long to get back to you. I'm in upgrade land over here. Yes the urls are the same and there are no special characters. If I copy and paste the url into my browser it works fine, but the same url from clicking the banner gives a 404. If it's not doing it for you it could be on my end. I'll investigate things a bit more. Thank you so much for checking it out. I'll let you know what I find. It's a great plugin and it's nice that it has been supported and updated for so long.

**Comment by BugBuster1701** [comment]
Can you test it with the new verision 1.0.1? I have found a problem with the cache.
But i'm afraid, that's not the problem for this issue.

**Comment by rburch** [comment]
Upgraded to 1.0.2 and tried again. The issue I was having seems to be fixed now.

**Comment by BugBuster1701** [comment]
Fixed #20
