### ISSUE TITLE
Contao 4.4.24: Installation fehlgeschlagen

### ISSUE THREAD

**Issue by chriza** [BugBuster1701/contao-banner-bundle#26]
die Installation der Extension hat folgenden Fehler geworfen:

In FileLoader.php line 168:

  [Semantical Error] The annotation "@Sensio\Bundle\FrameworkExtraBundle\Conf
  iguration\Route" in class BugBuster\BannerBundle\Controller\BannerFeControl
  ler does not exist, or could not be auto-loaded in /www/htdocs/w0146c19/web
  pages/svnrw/dev/vendor/bugbuster/contao-banner-bundle/src/Controller (which
   is being imported from "/www/htdocs/xxxxx/xxxx/xxxx/dev/vendor/bug
  buster/contao-banner-bundle/src/ContaoManager/../Resources/config/routing.y
  ml"). Make sure annotations are installed and enabled.

In AnnotationException.php line 54:

  [Semantical Error] The annotation "@Sensio\Bundle\FrameworkExtraBundle\Conf
  iguration\Route" in class BugBuster\BannerBundle\Controller\BannerFeControl
  ler does not exist, or could not be auto-loaded.

**Comment by BugBuster1701** [comment]
selbes Problem wie hier https://github.com/do-while/contao-BackupDB/issues/13

**Comment by BugBuster1701** [comment]
Fixed in version 1.0.4
