### ISSUE TITLE
Bildgrößen greifen nicht

### ISSUE THREAD

**Issue by akroii** [BugBuster1701/contao-banner-bundle#37]
Ich habe ein Logo mit dem Banner-Modul eingebunden und mit einer Bildgröße versehen.
![Bildschirmfoto 2019-07-01 um 15 55 55](https://user-images.githubusercontent.com/8830861/60442182-ca60cb00-9c18-11e9-890a-2b677c51a8f0.png)

Leider wird im Frontend die Größe nicht neu berechnet.
![Bildschirmfoto 2019-07-01 um 15 57 41](https://user-images.githubusercontent.com/8830861/60442263-f8dea600-9c18-11e9-9aa9-27e24630d84e.png)

Der Log gibt dazu keine Informationen preis.

Contao 4.4.37
Banner: 1.0.9

**Comment by BugBuster1701** [comment]
Wie kommt denn das Banner Bild in ein Template einer anderen Erweiterung?

**Comment by akroii** [comment]
Es ist das unveränderte mod_banner_list_all.html5

```
<!-- indexer::stop -->
<aside class="<?php echo $this->class; ?> block"<?php echo $this->cssID; ?><?php if ($this->style): ?> style="<?php echo $this->style; ?>"<?php endif; ?>>
<?php if (($this->headline) && (!$this->headline_stop)): ?>
<<?php echo $this->hl; ?>><?php echo $this->headline; ?></<?php echo $this->hl; ?>>
<?php endif; ?>
<?php foreach ($this->banners as $banner): ?>
<?php if ($banner['banner_pic']) : ?>
	<figure class="banner_wrap<?php echo $banner['banner_wrap_class']; ?>"<?php echo $banner['banner_wrap_id']; ?> itemscope itemtype="http://schema.org/ImageObject">
		<div class="banner_image" id="banner_<?php echo $banner['banner_id']; ?>">
			<?php if ($banner['banner_url']): ?><a href="<?= $this->route('bugbuster_banner_frontend_clicks') ?>?<?php echo $banner['banner_key'].$banner['banner_id']; ?>" <?php echo $banner['banner_target']; ?> title="<?php echo $banner['banner_comment']; ?>" itemprop="contentUrl"><?php endif; ?>
			<?php $this->insert('picture_default', $banner['picture']) ?>
			<?php if ($banner['banner_url']): ?></a><?php endif; ?>
		</div>
	    <figcaption class="banner_name" itemprop="caption"><?php echo $banner['banner_name']; ?></figcaption>
	</figure>
<?php endif; ?>
<?php if ($banner['banner_text']) : ?>
	<figure class="banner_wrap<?php echo $banner['banner_wrap_class']; ?>"<?php echo $banner['banner_wrap_id']; ?>>
	    <div class="banner_text" id="banner_<?php echo $banner['banner_id']; ?>">
	    	<div class="banner_text_name"><?php if ($banner['banner_url']): ?><a href="<?= $this->route('bugbuster_banner_frontend_clicks') ?>?<?php echo $banner['banner_key'].$banner['banner_id']; ?>" <?php echo $banner['banner_target']; ?> title="<?php echo $banner['banner_name']; ?>" ><?php endif; ?><?php echo $banner['banner_name']; ?><?php if ($banner['banner_url']): ?></a><?php endif; ?></div>
	    	<div class="banner_text_comment"><?php echo $banner['banner_comment']; ?></div>
	        <?php if ($banner['banner_url']): ?><div class="banner_text_url"><a href="<?= $this->route('bugbuster_banner_frontend_clicks') ?>?<?php echo $banner['banner_key'].$banner['banner_id']; ?>" <?php echo $banner['banner_target']; ?> title="<?php echo $banner['banner_name']; ?>" ><?php echo $banner['banner_url_kurz']; ?></a></div><?php endif; ?>
	    </div>
    </figure>
<?php endif; ?>
<?php if ($banner['banner_empty']) : ?>
	<div class="banner_empty">
	<!-- <?php echo $banner['banner_name']; ?> -->
	</div>
<?php endif; ?>
<?php endforeach; ?>
</aside>
<!-- indexer::continue -->

```

**Comment by BugBuster1701** [comment]
Die vordefinierten Größen werden wohl nicht übernommen.
Muss ich mir anschauen, kann sein , das es bisher gar nicht unterstützt wurde.

**Comment by BugBuster1701** [comment]
- [ ] Vordefinierte Größe, als numerischer Wert in "resize mode" von Contao gesetzt, auswerten
- [ ] height, width, resizeMode auslesen (weitere Angaben werden nicht unterstützt
- [ ] resizeMode anwenden, derzeit fest "proportional"

**Comment by BugBuster1701** [comment]
**Achtung:** Bugfix erfolgt erst in der Version 1.0.13 für Contao 4.7+, dann Backport in die Version 1.0.10.1 für Contao 4.4

**Comment by BugBuster1701** [comment]
resizeMode bei normaler Auswahl greift noch nicht

**Comment by BugBuster1701** [comment]
**Contao 4.4-4.6 Nutzer:** 
Um die Version 1.0.10.1 anzufordern im Contao Manager "^1.0.10" eingeben!

**Comment by akroii** [comment]
Es scheint noch nicht richtig zu funktionieren:

An der Stelle des Banners erhalte ich jetzt:
![Bildschirmfoto 2019-07-05 um 10 29 48](https://user-images.githubusercontent.com/8830861/60709069-d649d700-9f0f-11e9-9593-ca87259ee210.png)

Im Debug-Mode:

`CRITICAL10:25:25 | request | Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "contao.assets.files_context"." at /srv/www/wiesenmarkt/public/wiesenmarkt/contao-4-4-x/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php line 348`

**Comment by BugBuster1701** [comment]
Ah, mist, den Service gibt es erst ab 4.5.
Kommt gleich ne neue Version 1.0.10.2

**Comment by BugBuster1701** [comment]
Bitte mal ein Update machen, es sollte mit der 1.0.10.2 nun funktionieren.

**Comment by akroii** [comment]
Funktioniert, Danke!
