### ISSUE TITLE
Is this bundle use ImageSize?

### ISSUE THREAD

**Issue by hamidabbaszadeh** [BugBuster1701/contao-banner-bundle#48]
It seems that in banner `ImageSize` does not work [completely]? I mean it use only main ImageSize and not Media queries.

Also, it does not use `alt` and `title` form file Meta data.

**Comment by BugBuster1701** [comment]
`alt` and `title` are filled from the banner definition.
alt = Banner Name
title = Banner Comment
If these values are not set there, the meta data would be possible as an alternative. This would be a new feature.

Where do you define Media Queries?

**Comment by hamidabbaszadeh** [comment]
I used ImageSize but "Contao ImageSize Media Queries in Theme" not applied!

**Comment by hamidabbaszadeh** [comment]
And, imagesize does not work for `.gif` files.
