### ISSUE TITLE
Crawler also shows broken links on landing page subpages of banner destination URL

### ISSUE THREAD

**Issue by grashalm4u** [BugBuster1701/contao-banner-bundle#67]
Hello Bugbuster,

when I let the crawler in Contao search for broken links, numerous results come up where broken links are found on the target page of the respective banner target URL.
In the forum, Spooky said: "Perhaps the 301 redirection of the banner URLs is the problem. Since the banner URL could change at any time, perhaps 302 or 307 would be better here."
Since I don't understand enough about it, I'll post the link to the relevant thread here so you can read it again:

[https://community.contao.org/de/showthread.php?82581-Crawler-also-shows-broken-links-on-third-party-pages-from-landing-pages-of-the-banner-module-&p=555547#post555547](url)

grashalm

**Comment by BugBuster1701** [comment]
In the frontend module there is the setting if you want to have the redirection as 301 or 302. This is then valid for all banners.

**Comment by BugBuster1701** [comment]
Change default to 302.

**Comment by BugBuster1701** [comment]
In Version 1.3.3 verändert.
