### ISSUE TITLE
Attempted to call an undefined method named "rowCount" of class "Doctrine\DBAL\Statement"

### ISSUE THREAD

**Issue by bezin** [BugBuster1701/contao-banner-bundle#83]
The Version 120Update migration files in line 96 with the following error (Contao 4.13 / PHP 7.4): 

```
Attempted to call an undefined method named "rowCount" of class "Doctrine\DBAL\Statement"
```

The migration runs sucessful though, because the row count is only called for the final info :-)

**Comment by BugBuster1701** [comment]
Welche Version von Banner Bundle?
Weil der Fehler sollte schon in 1.5.0 behoben sein.
https://github.com/BugBuster1701/contao-banner-bundle/issues/79
Oder ist bei Dir eine doctrine/dbal Version <3 installiert?

**Comment by bezin** [comment]
Hallo, ich hab' versucht, es zu reproduzieren, konnte es aber leider nicht. Die Migration auf dem Live-Server lief problemlos durch. Ich hatte lokal schrittweise die PHP-Version angehoben – es kann gut sein, dass zwischendurch aufgrund des PHP Requirements DBAL in Version 2 installiert wurde. Ich schließe das Ticket daher 👍
