### ISSUE TITLE
Installation unter Contao 5.3 bricht ab

### ISSUE THREAD

**Issue by Schmidty2** [BugBuster1701/contao-banner-bundle#87]
Hallo,
die Installation unter Contao 5.3.1 bricht ab.
Contao 5.3.1
Provider All-Inkl
PHP 8.3.3
Ein Problem mit monolog.

> Problem 1
>     - symfony/http-foundation[v4.4.0, ..., v4.4.8] require php ^7.1.3 -> your php version (8.3.3.0) does not satisfy that requirement.
>     - monolog/monolog[2.0.0, ..., 2.0.2] require php ^7.2 -> your php version (8.3.3.0) does not satisfy that requirement.
>     - contao/core-bundle[4.9.0, ..., 4.10.4] require php ^7.2 -> your php version (8.3.3.0) does not satisfy that requirement.
>     - numero2/contao-proper-filenames[v2.1.0, ..., v2.1.6] require contao/core-bundle ^4.4.0 -> satisfiable by contao/core-bundle[4.4.0, ..., 4.13.38].
>     - contao/core-bundle[4.12.0, ..., 4.12.7] require symfony/http-foundation ^4.4 || ^5.2 -> satisfiable by symfony/http-foundation[v4.4.0, ..., v4.4.49, v5.2.0, ..., v5.4.35].
>     - contao/core-bundle[4.11.0, ..., 4.11.9] require symfony/http-foundation 4.4.* || 5.2.* -> satisfiable by symfony/http-foundation[v4.4.0, ..., v4.4.49, v5.2.0, ..., v5.2.14].
>     - contao/core-bundle[4.9.10, ..., 4.10.7] require symfony/http-foundation 4.4.* -> satisfiable by symfony/http-foundation[v4.4.0, ..., v4.4.49].
>     - contao/core-bundle[4.13.0, ..., 4.13.38] require symfony/http-client ^5.4 -> satisfiable by symfony/http-client[v5.4.0, ..., v5.4.37].
>     - symfony/http-client[v6.4.0, ..., v6.4.5] conflict with symfony/http-foundation v5.4.35.
>     - symfony/http-client[v6.4.0, ..., v6.4.5] conflict with symfony/http-foundation v5.4.13.
>     - symfony/http-client[v6.4.0, ..., v6.4.5] conflict with symfony/http-foundation v5.3.14.
>     - symfony/http-client[v6.4.0, ..., v6.4.5] conflict with symfony/http-foundation v5.3.3.
>     - symfony/http-client[v6.4.0, ..., v6.4.5] conflict with symfony/http-foundation v5.2.14.
>     - symfony/http-client[v6.4.0, ..., v6.4.5] conflict with symfony/http-foundation v5.2.11.
>     - symfony/http-client[v6.4.0, ..., v6.4.5] conflict with symfony/http-foundation v4.4.49.
>     - symfony/http-client[v6.4.0, ..., v6.4.5] conflict with symfony/http-foundation v4.4.46.
>     - symfony/http-client[v6.4.0, ..., v6.4.5] conflict with symfony/http-foundation v4.4.27.
>     - symfony/http-client[v6.4.0, ..., v6.4.5] conflict with symfony/http-foundation v4.4.26.
>     - symfony/http-client[v6.4.0, ..., v6.4.5] conflict with symfony/http-foundation v4.4.17.
>     - You can only install one version of a package, so only one of these can be installed: symfony/http-client[v4.3.6, ..., v4.4.51, v5.0.0, ..., v5.4.37, v6.0.0, ..., v6.4.5].
>     - contao/core-bundle 4.4.0 requires terminal42/header-replay-bundle ^1.0 -> satisfiable by terminal42/header-replay-bundle[1.0.0, ..., 1.5.3].
>     - bugbuster/contao-banner-bundle[1.6.0, ..., 1.6.1] require symfony/http-client ^6.4 -> satisfiable by symfony/http-client[v6.4.0, ..., v6.4.5].
>     - terminal42/header-replay-bundle[1.0.0, ..., 1.4.4] require php >=5.6,<8 -> your php version (8.3.3.0) does not satisfy that requirement.
>     - terminal42/header-replay-bundle[1.5.0, ..., 1.5.3] require php ^5.6 | ^7.0 -> your php version (8.3.3.0) does not satisfy that requirement.
>     - contao/core-bundle[4.4.1, ..., 4.4.17] require php ^5.6|^7.0 -> your php version (8.3.3.0) does not satisfy that requirement.
>     - contao/core-bundle[4.4.18, ..., 4.4.57] require php ^5.6 || ^7.0 -> your php version (8.3.3.0) does not satisfy that requirement.
>     - contao/core-bundle[4.5.0, ..., 4.8.8] require php ^7.1 -> your php version (8.3.3.0) does not satisfy that requirement.
>     - Root composer.json requires bugbuster/contao-banner-bundle ^1.6 -> satisfiable by bugbuster/contao-banner-bundle[1.6.0, 1.6.1].
>     - Root composer.json requires numero2/contao-proper-filenames ^2.1 -> satisfiable by numero2/contao-proper-filenames[v2.1.0, ..., v2.1.8].
>     - numero2/contao-proper-filenames[v2.1.7, ..., v2.1.8] require contao/core-bundle ^4.9 || ^5.0 -> satisfiable by contao/core-bundle[4.9.0, ..., 4.13.38, 5.0.0, ..., 5.3.1].
>     - contao/core-bundle[5.0.0, ..., 5.3.1] require monolog/monolog ^2.0 -> satisfiable by monolog/monolog[2.0.0, ..., 2.9.2].
>     - You can only install one version of a package, so only one of these can be installed: monolog/monolog[1.11.0, ..., 1.27.1, 2.0.0, ..., 2.9.2, 3.0.0, ..., 3.5.0].
>     - Conclusion: install monolog/monolog 3.5.0 (conflict analysis result)

**Comment by BugBuster1701** [comment]
Siehe https://github.com/BugBuster1701/contao-visitors-bundle/issues/162
